import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Banner from '@/components/Banner'
import { Product } from '@/type'
import Products from '@/components/Products'

const inter = Inter({ subsets: ['latin'] })

interface Props {
  productData: Product;
}

export default function Home({ productData }: Props) {
  // console.log('Index',productData)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar/>
        <Banner/>
        <Products productData={productData}/>
      </main>
    </>
  )
}



////////////////////// server side rendering  data fetching start here//////////////////////////

export const getServerSideProps = async () => {
  // after deployiong www.ecommerce.vercel/api/productdata
  const productData =await (await fetch("http://localhost:8000/api/productdata")).json();

  return {
    props: {
      productData,
    },
  };
};